[package]
name = "rusty_thermostat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "^1.0"
chrono = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
reqwest = "^0.11.17"
[dependencies.postgres]
version="^0.19"
features = ["with-uuid-1", "with-chrono-0_4", "with-serde_json-1"]
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-uuid" ] }