//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ChangeSource")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::manual_change_history::Entity")]
    ManualChangeHistory,
}

impl Related<super::manual_change_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ManualChangeHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
