//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "HVACactivity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub heating: bool,
    #[sea_orm(column_name = "heatLastChange")]
    pub heat_last_change: Option<DateTime>,
    pub cooling: bool,
    #[sea_orm(column_name = "coolLastChange")]
    pub cool_last_change: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::controllers::Entity")]
    Controllers,
    #[sea_orm(has_many = "super::zones::Entity")]
    Zones,
}

impl Related<super::controllers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Controllers.def()
    }
}

impl Related<super::zones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Zones.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
