//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

pub mod prelude;

pub mod alerts;
pub mod change_source;
pub mod communication;
pub mod controllers;
pub mod env_capability;
pub mod hva_cactivity;
pub mod manual_change_history;
pub mod pollution_reading;
pub mod schedules;
pub mod sensor_reading_history;
pub mod sensors;
pub mod weather_reading;
pub mod weekdays;
pub mod zones;
