//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Weekdays")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "Sunday")]
    pub sunday: bool,
    #[sea_orm(column_name = "Monday")]
    pub monday: bool,
    #[sea_orm(column_name = "Tuesday")]
    pub tuesday: bool,
    #[sea_orm(column_name = "Wednesday")]
    pub wednesday: bool,
    #[sea_orm(column_name = "Thursday")]
    pub thursday: bool,
    #[sea_orm(column_name = "Friday")]
    pub friday: bool,
    #[sea_orm(column_name = "Saturday")]
    pub saturday: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::schedules::Entity")]
    Schedules,
}

impl Related<super::schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Schedules.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
